### ISSUE TITLE
Assertion Equals fails on hash comparison

### ISSUE THREAD

**Issue by learod** [emancu/crotest#7]
In this code
```ruby 
  it "should say Hi!" do
    res = JSON.parse(response.body)
    assert_equal res, {"message" => "Hi!"}
  end
```

the output is 

```
 Failed:
	"should say Hi!" [../spec/followp_spec.cr:6]

	{"message" => "Hi!"} != {"message" => "Hi!"} (Crotest::AssertionFailed)
```

Both are the same value. Any Idea?

**Comment by emancu** [comment]
@learod interesting. Let me take a look during the day, and I will reply you back tonight.

**Comment by emancu** [comment]
@learod could you specify your crystal version?

**Comment by learod** [comment]
@emancu Crystal Version 0.18.7
Thanks

**Comment by emancu** [comment]
@learod You are missing a big difference here. Those look exactly the same, but they are from different type. You are comparing a `Hash(String, String)` with a `JSON::Any`

Let me share with you the following code, to explain better the situation

```crystal
require "json"

it "should say Hi!" do
  expected = { "message" => "Hi!" }
  body = "{\"message\":\"Hi!\"}"

  res = JSON.parse body
  res_hash = res.as_h

  assert_equal JSON::Any, res.class
  assert_equal Hash(String, JSON::Type), res_hash.class
  assert_equal Hash(String, String), expected.class

  # However, this is kind of tricky because this assert actually pass
  assert_equal expected, res

  # But this will fail
  assert_equal res, expected
end
```

You may want to take a look to the JSON module, and see how to properly parse your string.

https://crystal-lang.org/api/0.18.7/JSON.html
https://crystal-lang.org/api/0.18.7/JSON/Any.html

Also, you should ask on the IRC channel #crystal-lang why is this happening

```crystal
  require 'json'
  expected = { "message" => "Hi!" }
  body = "{\"message\":\"Hi!\"}"

  res = JSON.parse body

  puts expected == res # false
  puts res == expected # true
```

I'm closing this issue, because it is nothing wrong with crotest, but feel free to add any comment to complete the discussion
